# This is a sample .typo-ci.yml file, it's used to configure how Typo CI will behave.
# Add it to the root of your project and push it to github.
---

# What language dictionaries should it use? Currently Typo CI supports:
# de
# en
# en_GB
# es
# fr
# it
# pt
# pt_BR
dictionaries:
  - en
  - en_GB

# Any files/folders we should ignore?
excluded_files:
  - "vendor/**/*"
  - "node_modules/**/*"
  - "*.key"
  - "*.enc"
  - "*.min.css"
  - "*.css.map"
  - "*.min.js"
  - "*.js.map"
  - "*.mk"
  - "package-lock.json"
  - "yarn.lock"
  - "Gemfile.lock"
  - ".typo-ci.yml"
  - "/pdf/*.pdf"
  - "/.vscode/*.settings.json"

# Any typos we should ignore?
excluded_words:
  - typoci
  - Warez
  - Cloudflare
  - meme
  - CHEF-KOCH
  - IGG
  - Offline
  - Trackers
  - Public
  - Good-Old-Downloads
  - GIndex
  - GoIndex
  - Reddit
  - Microsoft
  - Discord
  - Riot
  - SpaceX
  - ZippyShare
  - Matrix
  - devbots
  - makepdfs
  - mkrakowitzer
  - actions-makepdfs
  - spyoungtech
  - Genration
  - Rosco
  - SzeneBox
  - szb
  - NZB
  - Kabel-Receiver
  - torrenting
  - Toorgle
  - remuxes
  - Animés
  - différents
  - dpstream
  - herbergeurs
  - votre
  - Filmz
  - alamy
  - gsettings
  - hoster
  - WawaCity
  - Streamcomplet
  - Wikiserie
  - Gratuit
  - Allostream
  - Série
  - Papystreaming
  - Filmcomplet
  - Serie-Streaming
  - Comédie
  - Horreur
  - Annuaire-telechargement-fr
  - Annuaire
  - Sokrostream
  - Mobdro
  - Megadede
  - Movidy
  - Regarder
  - complets
  - kkiboeco
  - XpoMusic
  - Spotify
  - Netflix
  - des
  - française
  - gratuit
  - SteamWorkFixs
  - Steam
  - les
  - sélections
  - voir
  - autres
  - gratuit
  - PCMYMJuegos
  - mangas
  - téléchargement
  - séries
  - CompucaliTV
  - monkrus
  - repacker

# Would you like filenames to also be spellchecked?
spellcheck_filenames: true
