# https://github.com/marketplace/actions/git-anti-virus-scan?version=2
on: [push]

jobs:
  gitavscan:
    runs-on: ubuntu-latest
    name: AV scan
    steps:
    - uses: actions/checkout@master
    - name: Git AV Scan
      uses: djdefi/gitavscan@master
